# Special prospector config file for the tests dir.
#
# Tests can contain mistakes, and should have consistent code style, so I do
# want to lint the tests, but I don't want to apply exactly the same lint rules
# to the tests as to the production code.
inherits:
    - .prospector.base
test-warnings: true
pylint:
  options:
    # Allow function and method names in tests to be longer and to contain
    # capital letters.
    function-rgx: "[a-zA-Z_][a-zA-Z0-9_]{2,70}$"
    method-rgx: "[a-zA-Z_][a-zA-Z0-9_]{2,70}$"
  disable:
    - no-self-use  # There are often reasons to group test methods into classes
                   # even if they don't use self.
    - redefined-outer-name # Pytest fixtures always break this rule.
ignore-paths:
  - lti/
